curl -XPUT 'http://localhost:9200/ci/name/1' -d '{"id": 11972,"name" : "Daniel Lee"   ,"cname":"李康善" ,"common" : "你好吗"}'
curl -XPUT 'http://localhost:9200/ci/name/2' -d '{"id": 36506,"name" : "Kuan Zhang"   ,"cname":"张宽"   ,"common" : "你好吗"}'
curl -XPUT 'http://localhost:9200/ci/name/3' -d '{"id": 36506,"name" : "ShengMing Dai","cname":"戴生明" ,"common" : "你好吗"}'
curl -XPUT 'http://localhost:9200/ci/name/4' -d '{"id": 49744,"name" : "Shuming Zhao" ,"cname":"赵树铭" ,"common" : "你好吗"}'
curl -XPUT 'http://localhost:9200/ci/name/5' -d '{"id": 67042,"name" : "Ming Chu"     ,"cname":"初明"   ,"common" : "你好吗"}'
curl -XPUT 'http://localhost:9200/ci/name/6' -d '{"id": 59712,"name" : "Qing ZHU"     ,"cname":"朱庆"   ,"common" : "你好吗"}'
